### ISSUE TITLE
No Suitable Kernel Found

### ISSUE THREAD

**Issue by soulslicer** [bmerry/mlsgpu#10]
I received the following error:
```

About 534MiB of device memory will be used per device.
Using device GeForce GTX 1070
Initializing...
Tuning radixsort for uint keys and 4 byte values on GeForce GTX 1070
......!
......
.......................................!!!
.................................
..!.!.........!
........
Tuning scan for uint elements on GeForce GTX 1070
...........
..........
...........!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!
no suitable kernel found
```

**Comment by bmerry** [comment]
Have you previously been able to run mlsgpu? Is this a new GPU or driver? It's possible that clogs doesn't work on the new Pascal GPUs, since I'm not doing any maintenance on it, and I don't have a Pascal GPU to test with.

**Comment by soulslicer** [comment]
i am testing this on a 1070 GTX

**Comment by bmerry** [comment]
I finally have access to a Pascal-based GPU and have investigated this. It is caused by a bug in the NVIDIA drivers, which I've now filed with NVIDIA.

**Comment by bmerry** [comment]
@soulslicer I've made a new CLOGS release (1.5.1) with a workaround for the NVIDIA bug. If that doesn't fix the problem for you, then reopen the issue.
